/**
 * Fetches the Bedrock foundation-model + inference-profile catalog and WRITES
 * packages/ai-bedrock/src/model-catalog.generated.ts so the committed file
 * stays fresh without manual editing.
 *
 * MAINTAINER-ONLY. Not run in CI. Requires AWS credentials (standard provider
 * chain) with bedrock:List* permissions, and the AWS SDK:
 *   pnpm add -Dw @aws-sdk/client-bedrock      # if not already installed
 *   AWS_REGION=us-east-1 pnpm tsx scripts/fetch-bedrock-models.ts
 *
 * Per-API flags (converse / chat / responses) come from the static seed file
 * scripts/bedrock-api-compatibility.json, transcribed from:
 * https://docs.aws.amazon.com/bedrock/latest/userguide/models-api-compatibility.html
 * Update the JSON seed to add new providers/models before re-running the script.
 *
 * Why manual: ListFoundationModels carries modalities + inference types but no
 * pricing, and per-account/region availability varies. The committed model-catalog
 * is the long-term source of truth; this script regenerates it automatically.
 */
import {
  BedrockClient,
  ListFoundationModelsCommand,
  ListInferenceProfilesCommand,
} from '@aws-sdk/client-bedrock'
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { join, dirname } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

interface CompatibilityRule {
  match: string
  converse: boolean
  chat: boolean
  responses: boolean
}

function loadCompatibilitySeed(): CompatibilityRule[] {
  const seedPath = join(__dirname, 'bedrock-api-compatibility.json')
  return JSON.parse(readFileSync(seedPath, 'utf-8')) as CompatibilityRule[]
}

function lookupApis(
  id: string,
  rules: CompatibilityRule[],
): { converse: boolean; chat: boolean; responses: boolean } {
  for (const rule of rules) {
    if (id.includes(rule.match)) {
      return {
        converse: rule.converse,
        chat: rule.chat,
        responses: rule.responses,
      }
    }
  }
  // Default: Converse is supported by virtually all text models; chat/responses are opt-in.
  return { converse: true, chat: false, responses: false }
}

function emitCatalog(
  entries: Array<{
    id: string
    profileId?: string
    input: string[]
    output: string[]
    apis: { converse: boolean; chat: boolean; responses: boolean }
  }>,
): string {
  const lines: string[] = [
    `// GENERATED by scripts/fetch-bedrock-models.ts — do not edit by hand.`,
    `// Refresh: AWS_REGION=us-east-1 pnpm tsx scripts/fetch-bedrock-models.ts`,
    `export const GENERATED_BEDROCK_MODELS = [`,
  ]

  for (const entry of entries) {
    const inputLiteral = entry.input.map((m) => `'${m}'`).join(', ')
    const outputLiteral = entry.output.map((m) => `'${m}'`).join(', ')
    const apis = entry.apis

    const profilePart =
      entry.profileId !== undefined ? `profileId: '${entry.profileId}', ` : ''

    lines.push(
      `  { id: '${entry.id}', ${profilePart}input: [${inputLiteral}], output: [${outputLiteral}], apis: { converse: ${apis.converse}, chat: ${apis.chat}, responses: ${apis.responses} } },`,
    )
  }

  lines.push(`] as const`, ``)
  return lines.join('\n')
}

async function main() {
  const region = process.env['AWS_REGION'] ?? 'us-east-1'
  const client = new BedrockClient({ region })
  const compatRules = loadCompatibilitySeed()

  // ListFoundationModels typically returns no nextToken, but loop on it anyway
  // so we stay correct if it ever paginates.
  const modelSummaries = []
  let modelsToken: string | undefined
  do {
    const page = await client.send(
      new ListFoundationModelsCommand({
        byOutputModality: 'TEXT',
        ...(modelsToken ? { nextToken: modelsToken } : {}),
      }),
    )
    modelSummaries.push(...(page.modelSummaries ?? []))
    modelsToken = page.nextToken
  } while (modelsToken)

  // ListInferenceProfiles is paginated — collect every page via nextToken.
  const inferenceProfileSummaries = []
  let profilesToken: string | undefined
  do {
    const page = await client.send(
      new ListInferenceProfilesCommand(
        profilesToken ? { nextToken: profilesToken } : {},
      ),
    )
    inferenceProfileSummaries.push(...(page.inferenceProfileSummaries ?? []))
    profilesToken = page.nextToken
  } while (profilesToken)

  // Build a lookup: base model id → preferred cross-region inference profile id.
  // A cross-region profile id typically looks like "us.<baseModelId>".
  const profileByBaseId = new Map<string, string>()
  for (const profile of inferenceProfileSummaries) {
    const profileId = profile.inferenceProfileId
    if (!profileId) continue
    // Strip the leading region prefix (e.g. "us.", "eu.", "ap.") to get the base id.
    const baseId = profileId.replace(/^(us|eu|ap)\./, '')
    if (!profileByBaseId.has(baseId)) {
      profileByBaseId.set(baseId, profileId)
    }
  }

  const textModels = modelSummaries
    .filter((m) => (m.outputModalities ?? []).includes('TEXT'))
    .map((m) => {
      const id = m.modelId ?? ''
      return {
        id,
        input: (m.inputModalities ?? []).map((x) => x.toLowerCase()),
      }
    })
    .filter((m) => m.id.length > 0)

  const entries = textModels.map((m) => {
    const profileId = profileByBaseId.get(m.id)
    const resolvedId = profileId ?? m.id
    const apis = lookupApis(resolvedId, compatRules)

    const entry: {
      id: string
      profileId?: string
      input: string[]
      output: string[]
      apis: { converse: boolean; chat: boolean; responses: boolean }
    } = {
      id: resolvedId,
      input: m.input,
      output: ['text'],
      apis,
    }

    if (profileId !== undefined) {
      entry.profileId = profileId
    }

    return entry
  })

  const outPath = join(
    ROOT,
    'packages',
    'ai-bedrock',
    'src',
    'model-catalog.generated.ts',
  )
  const content = emitCatalog(entries)
  writeFileSync(outPath, content, 'utf-8')
  console.log(`Wrote ${entries.length} models to ${outPath}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
